apiVersion: v1
kind: Namespace
metadata:
  name: metrics
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager  
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki  