apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- helm-repository.yaml
#- helm-release.yaml
- cert-manager.crds.yaml
- ca-key-pair.yaml
- ca-cluster-issuer.yaml