apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  releaseName: loki
  chart:
    spec:
      version: "2.8.2"
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: emrahkk-github-io
  interval: 5m
  values:
    loki:
      config:
        compactor:
          shared_store: s3
          working_directory: /data/loki/boltdb-shipper-compactor
        schema_config:
          configs:
          - from: "2020-10-24"
            index:
              period: 24h
              prefix: index_
            object_store: aws
            schema: v11
            store: boltdb-shipper
        storage_config:
          aws:
            s3: http://admin:Admin123456#$!@minio-release.minio.svc.cluster.local:9000/loki
            s3forcepathstyle: true
          boltdb_shipper:
            active_index_directory: /data/loki/boltdb-shipper-active
            cache_location: /data/loki/boltdb-shipper-cache
            cache_ttl: 24h
            shared_store: s3
